### ISSUE TITLE
Add a composer.json

### ISSUE THREAD

**Issue by erikdonohoo** [qencode-dev/qencode-api-php-client#1]
Anyway you guys could add a composer.json file to this repo so it can be depended on by PHP projects? As is I basically have to copy your code into mine in order to use this.  Do you have any suggestions?

**Comment by stevecoug** [comment]
With a proper composer.json file, the autoload.php wouldn't be necessary.

**Comment by stevecoug** [comment]
https://packagist.org/ has instructions for doing this (under Publishing Packages).

**Comment by qencode-dev** [comment]
@erikdonohoo @stevecoug 
Please check composer stuff we added. Usage described in readme.md:

Get composer, run this in your project directory:
```bash
    curl -sS https://getcomposer.org/installer | php
```
Create composer.json under the root of your project with the following instructions:
```json
    {
      "require": {
        "qencode/api-client": "1.0.*"
      },
      "autoload": {
        "classmap": [
          "vendor/qencode/api-client/src/"
        ]
      }
    }
```
Run composer:
```php
    php composer.phar install
```
Include vendor/autoload.php:
```php
   require 'vendor/autoload.php';
```

**Comment by stevecoug** [comment]
The autoload section of composer.json should be in your composer.json, not the code using it. The code using it should just have the require section.

Also, you should add vendor/ to your .gitignore.

**Comment by qencode-dev** [comment]
Moved autoload section to vendor composer.json.
Added vendor/ to .gitignore
Please use version 1.01.* in your composer.json
