### ISSUE TITLE
How to Check Status on Submitted Job

### ISSUE THREAD

**Issue by lgrrealag** [qencode-dev/qencode-api-php-client#3]
The examples all check the status of a task just after it was submitted. I need to check the status of a task at a later point in time not  just when it is submitted and not sit waiting around for it to finish. This means the last task might not be the task I need to check the status on. It looks like I can do this with CURL using the task token but the PHP client has the task token set to private and not 
available. Is there any way to get a previous task status using this SDK? Is there any issues that might arise if I set the $taskToken to public so it can then be saved and used later to check on the status using CURL?

I realize that a callback might be used but it is possible that where we are planning to run this will not be publicly accessible so a callback is not an option.

**Comment by qencode-dev** [comment]
Hi @lgrrealag 
Thanks for your question. Actually you can get task token value using this call:

`$task->getTaskToken()`

Here's an example of how you can get status of any task with task token:

```
<?php
require_once __DIR__ . '/../autoload.php';

use Qencode\Exceptions\QencodeApiException;
use Qencode\Exceptions\QencodeException;
use Qencode\QencodeApiClient;
use Qencode\Classes\TranscodingTask;

$api_endpoint = 'https://api.qencode.com';
$apiKey = '...';
$task_token = '...';
$status_url = $api_endpoint.'/v1/status';
$q = new QencodeApiClient($apiKey, $api_endpoint);

$params = array('task_tokens[]' => $task_token);
$response = $q->post($status_url, $params);
$status = $response['statuses'][$task_token];
if ($status == null) {
    throw new QencodeClientException('Task '. $task_token. ' not found!');
}
if (array_key_exists('status_url', $status)) {
    $status_url = $status['status_url'];
}
print_r($status);
```

**Comment by lgrrealag** [comment]
Thanks. That helped a lot. Appreciate it.
