### ISSUE TITLE
Output file

### ISSUE THREAD

**Issue by vahidzoli** [qencode-dev/qencode-api-php-client#4]
i used trial version of qencode,
everything is ok but i can't find good endpoint in API for get output file.
how can i do?

**Comment by qencode-dev** [comment]
Hi @vahidzoli, sorry for late reply here. Unfortunately your question is not clear. If you need an URL for the output file, you can get it with /v1/status API method, or just by getting task status with any of SDK we provide.
Please let us know if you need any help with this.
